version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: dev
  assignees:
  - mkay-sh
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.41
    - 15.0.0
  - dependency-name: "@sentry/angular"
    versions:
    - 6.1.0
    - 6.2.1
    - 6.3.0
    - 6.3.1
  - dependency-name: core-js
    versions:
    - 3.10.2
    - 3.11.0
  - dependency-name: "@angular/language-service"
    versions:
    - 11.2.11
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.9
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1102.2
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
    - 0.1102.9
  - dependency-name: "@angular/cli"
    versions:
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
  - dependency-name: "@angular-devkit/schematics-cli"
    versions:
    - 0.1101.2
    - 0.1101.3
    - 0.1101.4
    - 0.1102.0
    - 0.1102.1
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
  - dependency-name: "@angular-devkit/architect"
    versions:
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
  - dependency-name: material-icons
    versions:
    - 0.5.4
    - 0.5.5
    - 0.6.0
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.1
    - 26.5.3
  - dependency-name: cypress
    versions:
    - 5.6.0
    - 6.4.0
    - 6.6.0
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.8
  - dependency-name: canvas
    versions:
    - 2.7.0
  - dependency-name: "@nrwl/nx-plugin"
    versions:
    - 11.4.0
  - dependency-name: ng-packagr
    versions:
    - 11.2.4
  - dependency-name: "@nrwl/angular"
    versions:
    - 11.4.0
  - dependency-name: "@nrwl/cli"
    versions:
    - 11.4.0
  - dependency-name: typescript
    versions:
    - 4.0.7
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.168
  - dependency-name: ini
    versions:
    - 1.3.6
  - dependency-name: prettier
    versions:
    - 2.2.1
